# Generated by Django 4.2.6 on 2023-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('surname', models.CharField(max_length=255, verbose_name='Soyad')),
                ('location', models.CharField(max_length=255, verbose_name='Ünvan')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Məlumat')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('date', models.CharField(max_length=255, verbose_name='Tarix')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='Adı')),
                ('degree', models.CharField(max_length=255, verbose_name='Dərəcə')),
                ('date_interval', models.CharField(max_length=255, verbose_name='Tarix')),
                ('profession', models.CharField(max_length=255, verbose_name='Ixtisas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Təhsil',
                'verbose_name_plural': 'Təhsil',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Pozisiya')),
                ('date_interval', models.CharField(max_length=255, verbose_name='Tarix')),
                ('company_name', models.CharField(max_length=255, verbose_name='Şirkət adı')),
                ('info', models.TextField(verbose_name='Məlumat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Iş təcrübəsi',
                'verbose_name_plural': 'Iş təcrübəsi',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Məlumat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Maraq',
                'verbose_name_plural': 'Maraq',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('image', models.ImageField(upload_to='media/')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Link')),
                ('info', models.TextField(verbose_name='Məlumat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Proyekt',
                'verbose_name_plural': 'Proyektlər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=255, verbose_name='Bacarıq')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bacarıq',
                'verbose_name_plural': 'Bacarıqlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('tiktok', 'Tiktok'), ('telegram', 'Telegram'), ('linkedin', 'linkedin')], max_length=255, verbose_name='Sosial media')),
                ('social_link', models.TextField(verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sosial media',
                'verbose_name_plural': 'Sosial media hesabları',
                'ordering': ('-created_at',),
            },
        ),
    ]
