# Generated by Django 4.2.6 on 2023-11-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='awards',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
