# Generated by Django 4.2.6 on 2023-11-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_awards_active_awards_created_at_awards_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('tiktok', 'Tiktok'), ('telegram', 'Telegram'), ('linkedin', 'linkedin'), ('github', 'GitHub')], max_length=255, verbose_name='Sosial media'),
        ),
    ]
